// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/analysis/v1/analysis_interface.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       int64    `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Uid      string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	OrigH    string   `protobuf:"bytes,3,opt,name=orig_h,json=origH,proto3" json:"orig_h,omitempty"`
	RespH    string   `protobuf:"bytes,4,opt,name=resp_h,json=respH,proto3" json:"resp_h,omitempty"`
	Domain   string   `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Proto    string   `protobuf:"bytes,6,opt,name=proto,proto3" json:"proto,omitempty"`
	Area     string   `protobuf:"bytes,7,opt,name=area,proto3" json:"area,omitempty"`
	Keywords []string `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Category string   `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Emotion  int32    `protobuf:"varint,10,opt,name=emotion,proto3" json:"emotion,omitempty"`
	OpId     int64    `protobuf:"varint,11,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
}

func (x *AnalysisInfo) Reset() {
	*x = AnalysisInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisInfo) ProtoMessage() {}

func (x *AnalysisInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisInfo.ProtoReflect.Descriptor instead.
func (*AnalysisInfo) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisInfo) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *AnalysisInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AnalysisInfo) GetOrigH() string {
	if x != nil {
		return x.OrigH
	}
	return ""
}

func (x *AnalysisInfo) GetRespH() string {
	if x != nil {
		return x.RespH
	}
	return ""
}

func (x *AnalysisInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AnalysisInfo) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *AnalysisInfo) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *AnalysisInfo) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *AnalysisInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AnalysisInfo) GetEmotion() int32 {
	if x != nil {
		return x.Emotion
	}
	return 0
}

func (x *AnalysisInfo) GetOpId() int64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

type GetAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAnalysisRequest) Reset() {
	*x = GetAnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisRequest) ProtoMessage() {}

func (x *GetAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnalysisRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAnalysisReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *AnalysisInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetAnalysisReply) Reset() {
	*x = GetAnalysisReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnalysisReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisReply) ProtoMessage() {}

func (x *GetAnalysisReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisReply.ProtoReflect.Descriptor instead.
func (*GetAnalysisReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnalysisReply) GetInfo() *AnalysisInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort     string `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	SortType string `protobuf:"bytes,2,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Current  int64  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Domain   string `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Uid      string `protobuf:"bytes,6,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ListAnalysisRequest) Reset() {
	*x = ListAnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysisRequest) ProtoMessage() {}

func (x *ListAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysisRequest.ProtoReflect.Descriptor instead.
func (*ListAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{3}
}

func (x *ListAnalysisRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListAnalysisRequest) GetSortType() string {
	if x != nil {
		return x.SortType
	}
	return ""
}

func (x *ListAnalysisRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAnalysisRequest) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListAnalysisRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListAnalysisRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ListAnalysisReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*AnalysisInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	Total int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListAnalysisReply) Reset() {
	*x = ListAnalysisReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnalysisReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysisReply) ProtoMessage() {}

func (x *ListAnalysisReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysisReply.ProtoReflect.Descriptor instead.
func (*ListAnalysisReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{4}
}

func (x *ListAnalysisReply) GetInfos() []*AnalysisInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ListAnalysisReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RunAnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunAnalysisRequest) Reset() {
	*x = RunAnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAnalysisRequest) ProtoMessage() {}

func (x *RunAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAnalysisRequest.ProtoReflect.Descriptor instead.
func (*RunAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{5}
}

type RunAnalysisReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunAnalysisReply) Reset() {
	*x = RunAnalysisReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunAnalysisReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAnalysisReply) ProtoMessage() {}

func (x *RunAnalysisReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAnalysisReply.ProtoReflect.Descriptor instead.
func (*RunAnalysisReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{6}
}

type EmotionNoticeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmotionNoticeRequest) Reset() {
	*x = EmotionNoticeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmotionNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionNoticeRequest) ProtoMessage() {}

func (x *EmotionNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionNoticeRequest.ProtoReflect.Descriptor instead.
func (*EmotionNoticeRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{7}
}

type EmotionNoticeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EmotionNoticeReply) Reset() {
	*x = EmotionNoticeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmotionNoticeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionNoticeReply) ProtoMessage() {}

func (x *EmotionNoticeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionNoticeReply.ProtoReflect.Descriptor instead.
func (*EmotionNoticeReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{8}
}

func (x *EmotionNoticeReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmotionNoticeReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Top10CategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Top10CategoryRequest) Reset() {
	*x = Top10CategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Top10CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top10CategoryRequest) ProtoMessage() {}

func (x *Top10CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top10CategoryRequest.ProtoReflect.Descriptor instead.
func (*Top10CategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{9}
}

type Top10 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Top10) Reset() {
	*x = Top10{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Top10) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top10) ProtoMessage() {}

func (x *Top10) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top10.ProtoReflect.Descriptor instead.
func (*Top10) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{10}
}

func (x *Top10) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Top10) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Top10Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Top10 []*Top10 `protobuf:"bytes,1,rep,name=top10,proto3" json:"top10,omitempty"`
}

func (x *Top10Reply) Reset() {
	*x = Top10Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Top10Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top10Reply) ProtoMessage() {}

func (x *Top10Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top10Reply.ProtoReflect.Descriptor instead.
func (*Top10Reply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{11}
}

func (x *Top10Reply) GetTop10() []*Top10 {
	if x != nil {
		return x.Top10
	}
	return nil
}

type Top10AreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Top10AreaRequest) Reset() {
	*x = Top10AreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Top10AreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top10AreaRequest) ProtoMessage() {}

func (x *Top10AreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top10AreaRequest.ProtoReflect.Descriptor instead.
func (*Top10AreaRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{12}
}

type Top10KeywordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Top10KeywordsRequest) Reset() {
	*x = Top10KeywordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Top10KeywordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top10KeywordsRequest) ProtoMessage() {}

func (x *Top10KeywordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top10KeywordsRequest.ProtoReflect.Descriptor instead.
func (*Top10KeywordsRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{13}
}

type EmotionDistributeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmotionDistributeRequest) Reset() {
	*x = EmotionDistributeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmotionDistributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionDistributeRequest) ProtoMessage() {}

func (x *EmotionDistributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionDistributeRequest.ProtoReflect.Descriptor instead.
func (*EmotionDistributeRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{14}
}

type EmotionDistributeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Positive int64 `protobuf:"varint,1,opt,name=positive,proto3" json:"positive,omitempty"`
	Neutral  int64 `protobuf:"varint,2,opt,name=neutral,proto3" json:"neutral,omitempty"`
	Negative int64 `protobuf:"varint,3,opt,name=negative,proto3" json:"negative,omitempty"`
}

func (x *EmotionDistributeReply) Reset() {
	*x = EmotionDistributeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmotionDistributeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionDistributeReply) ProtoMessage() {}

func (x *EmotionDistributeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_analysis_interface_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionDistributeReply.ProtoReflect.Descriptor instead.
func (*EmotionDistributeReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_analysis_interface_proto_rawDescGZIP(), []int{15}
}

func (x *EmotionDistributeReply) GetPositive() int64 {
	if x != nil {
		return x.Positive
	}
	return 0
}

func (x *EmotionDistributeReply) GetNeutral() int64 {
	if x != nil {
		return x.Neutral
	}
	return 0
}

func (x *EmotionDistributeReply) GetNegative() int64 {
	if x != nil {
		return x.Negative
	}
	return 0
}

var File_api_analysis_v1_analysis_interface_proto protoreflect.FileDescriptor

var file_api_analysis_v1_analysis_interface_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x02, 0x0a, 0x0c, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x5f, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72,
	0x69, 0x67, 0x48, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x73, 0x70, 0x48, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13,
	0x0a, 0x05, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6f,
	0x70, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x31, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0xa7, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x11, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x33, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x75,
	0x6e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x12,
	0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x16, 0x0a, 0x14,
	0x54, 0x6f, 0x70, 0x31, 0x30, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x31, 0x30, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x0a, 0x54, 0x6f, 0x70, 0x31, 0x30,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x31, 0x30, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x31, 0x30, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x31, 0x30, 0x22, 0x12, 0x0a, 0x10, 0x54, 0x6f, 0x70, 0x31, 0x30, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x6f, 0x70, 0x31, 0x30,
	0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1a, 0x0a, 0x18, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x16, 0x45,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x76, 0x65, 0x32, 0xe1, 0x07, 0x0a, 0x11, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x69, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x72, 0x0a,
	0x0b, 0x52, 0x75, 0x6e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x75, 0x6e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x1a, 0x10, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x75, 0x6e, 0x3a, 0x01,
	0x2a, 0x12, 0x78, 0x0a, 0x0d, 0x54, 0x6f, 0x70, 0x31, 0x30, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x31, 0x30, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x31,
	0x30, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b,
	0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x2f, 0x74, 0x6f, 0x70, 0x31, 0x30, 0x12, 0x6c, 0x0a, 0x09, 0x54,
	0x6f, 0x70, 0x31, 0x30, 0x41, 0x72, 0x65, 0x61, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x31, 0x30,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f,
	0x70, 0x31, 0x30, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19,
	0x12, 0x17, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x72, 0x65, 0x61, 0x2f, 0x74, 0x6f, 0x70, 0x31, 0x30, 0x12, 0x78, 0x0a, 0x0d, 0x54, 0x6f, 0x70,
	0x31, 0x30, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70,
	0x31, 0x30, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x31, 0x30, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x74, 0x6f,
	0x70, 0x31, 0x30, 0x12, 0x90, 0x01, 0x0a, 0x11, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x0d, 0x45, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x70, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x6e, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x24, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x42, 0x20, 0x5a, 0x1e, 0x70,
	0x6f, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_analysis_v1_analysis_interface_proto_rawDescOnce sync.Once
	file_api_analysis_v1_analysis_interface_proto_rawDescData = file_api_analysis_v1_analysis_interface_proto_rawDesc
)

func file_api_analysis_v1_analysis_interface_proto_rawDescGZIP() []byte {
	file_api_analysis_v1_analysis_interface_proto_rawDescOnce.Do(func() {
		file_api_analysis_v1_analysis_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_analysis_v1_analysis_interface_proto_rawDescData)
	})
	return file_api_analysis_v1_analysis_interface_proto_rawDescData
}

var file_api_analysis_v1_analysis_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_analysis_v1_analysis_interface_proto_goTypes = []interface{}{
	(*AnalysisInfo)(nil),             // 0: api.analysis.v1.AnalysisInfo
	(*GetAnalysisRequest)(nil),       // 1: api.analysis.v1.GetAnalysisRequest
	(*GetAnalysisReply)(nil),         // 2: api.analysis.v1.GetAnalysisReply
	(*ListAnalysisRequest)(nil),      // 3: api.analysis.v1.ListAnalysisRequest
	(*ListAnalysisReply)(nil),        // 4: api.analysis.v1.ListAnalysisReply
	(*RunAnalysisRequest)(nil),       // 5: api.analysis.v1.RunAnalysisRequest
	(*RunAnalysisReply)(nil),         // 6: api.analysis.v1.RunAnalysisReply
	(*EmotionNoticeRequest)(nil),     // 7: api.analysis.v1.EmotionNoticeRequest
	(*EmotionNoticeReply)(nil),       // 8: api.analysis.v1.EmotionNoticeReply
	(*Top10CategoryRequest)(nil),     // 9: api.analysis.v1.Top10CategoryRequest
	(*Top10)(nil),                    // 10: api.analysis.v1.Top10
	(*Top10Reply)(nil),               // 11: api.analysis.v1.Top10Reply
	(*Top10AreaRequest)(nil),         // 12: api.analysis.v1.Top10AreaRequest
	(*Top10KeywordsRequest)(nil),     // 13: api.analysis.v1.Top10KeywordsRequest
	(*EmotionDistributeRequest)(nil), // 14: api.analysis.v1.EmotionDistributeRequest
	(*EmotionDistributeReply)(nil),   // 15: api.analysis.v1.EmotionDistributeReply
}
var file_api_analysis_v1_analysis_interface_proto_depIdxs = []int32{
	0,  // 0: api.analysis.v1.GetAnalysisReply.info:type_name -> api.analysis.v1.AnalysisInfo
	0,  // 1: api.analysis.v1.ListAnalysisReply.infos:type_name -> api.analysis.v1.AnalysisInfo
	10, // 2: api.analysis.v1.Top10Reply.top10:type_name -> api.analysis.v1.Top10
	5,  // 3: api.analysis.v1.AnalysisInterface.RunAnalysis:input_type -> api.analysis.v1.RunAnalysisRequest
	9,  // 4: api.analysis.v1.AnalysisInterface.Top10Category:input_type -> api.analysis.v1.Top10CategoryRequest
	12, // 5: api.analysis.v1.AnalysisInterface.Top10Area:input_type -> api.analysis.v1.Top10AreaRequest
	13, // 6: api.analysis.v1.AnalysisInterface.Top10Keywords:input_type -> api.analysis.v1.Top10KeywordsRequest
	14, // 7: api.analysis.v1.AnalysisInterface.EmotionDistribute:input_type -> api.analysis.v1.EmotionDistributeRequest
	7,  // 8: api.analysis.v1.AnalysisInterface.EmotionNotice:input_type -> api.analysis.v1.EmotionNoticeRequest
	1,  // 9: api.analysis.v1.AnalysisInterface.GetAnalysis:input_type -> api.analysis.v1.GetAnalysisRequest
	3,  // 10: api.analysis.v1.AnalysisInterface.ListAnalysis:input_type -> api.analysis.v1.ListAnalysisRequest
	6,  // 11: api.analysis.v1.AnalysisInterface.RunAnalysis:output_type -> api.analysis.v1.RunAnalysisReply
	11, // 12: api.analysis.v1.AnalysisInterface.Top10Category:output_type -> api.analysis.v1.Top10Reply
	11, // 13: api.analysis.v1.AnalysisInterface.Top10Area:output_type -> api.analysis.v1.Top10Reply
	11, // 14: api.analysis.v1.AnalysisInterface.Top10Keywords:output_type -> api.analysis.v1.Top10Reply
	15, // 15: api.analysis.v1.AnalysisInterface.EmotionDistribute:output_type -> api.analysis.v1.EmotionDistributeReply
	8,  // 16: api.analysis.v1.AnalysisInterface.EmotionNotice:output_type -> api.analysis.v1.EmotionNoticeReply
	2,  // 17: api.analysis.v1.AnalysisInterface.GetAnalysis:output_type -> api.analysis.v1.GetAnalysisReply
	4,  // 18: api.analysis.v1.AnalysisInterface.ListAnalysis:output_type -> api.analysis.v1.ListAnalysisReply
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_analysis_v1_analysis_interface_proto_init() }
func file_api_analysis_v1_analysis_interface_proto_init() {
	if File_api_analysis_v1_analysis_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_analysis_v1_analysis_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnalysisReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnalysisReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunAnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunAnalysisReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmotionNoticeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmotionNoticeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Top10CategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Top10); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Top10Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Top10AreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Top10KeywordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmotionDistributeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_analysis_interface_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmotionDistributeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_analysis_v1_analysis_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_analysis_v1_analysis_interface_proto_goTypes,
		DependencyIndexes: file_api_analysis_v1_analysis_interface_proto_depIdxs,
		MessageInfos:      file_api_analysis_v1_analysis_interface_proto_msgTypes,
	}.Build()
	File_api_analysis_v1_analysis_interface_proto = out.File
	file_api_analysis_v1_analysis_interface_proto_rawDesc = nil
	file_api_analysis_v1_analysis_interface_proto_goTypes = nil
	file_api_analysis_v1_analysis_interface_proto_depIdxs = nil
}
