// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/analysis/v1/refactor_interface.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_RUNNING Status = 0
	Status_HANGING Status = 1
	Status_STOP    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "RUNNING",
		1: "HANGING",
		2: "STOP",
	}
	Status_value = map[string]int32{
		"RUNNING": 0,
		"HANGING": 1,
		"STOP":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_analysis_v1_refactor_interface_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_analysis_v1_refactor_interface_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{0}
}

type RefactorRefactorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dir        string `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Day        int64  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	BeginHour  int32  `protobuf:"varint,5,opt,name=begin_hour,json=beginHour,proto3" json:"begin_hour,omitempty"`
	EndHour    int32  `protobuf:"varint,6,opt,name=end_hour,json=endHour,proto3" json:"end_hour,omitempty"`
	Md5        string `protobuf:"bytes,7,opt,name=md5,proto3" json:"md5,omitempty"`
	CreateTime int64  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime int64  `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *RefactorRefactorInfo) Reset() {
	*x = RefactorRefactorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefactorRefactorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefactorRefactorInfo) ProtoMessage() {}

func (x *RefactorRefactorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefactorRefactorInfo.ProtoReflect.Descriptor instead.
func (*RefactorRefactorInfo) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{0}
}

func (x *RefactorRefactorInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RefactorRefactorInfo) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *RefactorRefactorInfo) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *RefactorRefactorInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RefactorRefactorInfo) GetBeginHour() int32 {
	if x != nil {
		return x.BeginHour
	}
	return 0
}

func (x *RefactorRefactorInfo) GetEndHour() int32 {
	if x != nil {
		return x.EndHour
	}
	return 0
}

func (x *RefactorRefactorInfo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *RefactorRefactorInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RefactorRefactorInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type RecapRefactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecapRefactorRequest) Reset() {
	*x = RecapRefactorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecapRefactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecapRefactorRequest) ProtoMessage() {}

func (x *RecapRefactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecapRefactorRequest.ProtoReflect.Descriptor instead.
func (*RecapRefactorRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{1}
}

type RecapRefactorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  Status `protobuf:"varint,1,opt,name=status,proto3,enum=api.refactor.v1.Status" json:"status,omitempty"`
	Running int32  `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Success int32  `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Failed  int32  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	Waiting int32  `protobuf:"varint,5,opt,name=waiting,proto3" json:"waiting,omitempty"`
}

func (x *RecapRefactorReply) Reset() {
	*x = RecapRefactorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecapRefactorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecapRefactorReply) ProtoMessage() {}

func (x *RecapRefactorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecapRefactorReply.ProtoReflect.Descriptor instead.
func (*RecapRefactorReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{2}
}

func (x *RecapRefactorReply) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_RUNNING
}

func (x *RecapRefactorReply) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *RecapRefactorReply) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *RecapRefactorReply) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *RecapRefactorReply) GetWaiting() int32 {
	if x != nil {
		return x.Waiting
	}
	return 0
}

type GetRefactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRefactorRequest) Reset() {
	*x = GetRefactorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRefactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefactorRequest) ProtoMessage() {}

func (x *GetRefactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefactorRequest.ProtoReflect.Descriptor instead.
func (*GetRefactorRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{3}
}

func (x *GetRefactorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRefactorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *RefactorRefactorInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetRefactorReply) Reset() {
	*x = GetRefactorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRefactorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefactorReply) ProtoMessage() {}

func (x *GetRefactorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefactorReply.ProtoReflect.Descriptor instead.
func (*GetRefactorReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{4}
}

func (x *GetRefactorReply) GetInfo() *RefactorRefactorInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListRefactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort     string `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	SortType string `protobuf:"bytes,2,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Current  int64  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Id       int64  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Day      int64  `protobuf:"varint,6,opt,name=day,proto3" json:"day,omitempty"`
	Dir      string `protobuf:"bytes,7,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *ListRefactorRequest) Reset() {
	*x = ListRefactorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRefactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefactorRequest) ProtoMessage() {}

func (x *ListRefactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefactorRequest.ProtoReflect.Descriptor instead.
func (*ListRefactorRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{5}
}

func (x *ListRefactorRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListRefactorRequest) GetSortType() string {
	if x != nil {
		return x.SortType
	}
	return ""
}

func (x *ListRefactorRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRefactorRequest) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListRefactorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListRefactorRequest) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ListRefactorRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ListRefactorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*RefactorRefactorInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	Total int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListRefactorReply) Reset() {
	*x = ListRefactorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRefactorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRefactorReply) ProtoMessage() {}

func (x *ListRefactorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRefactorReply.ProtoReflect.Descriptor instead.
func (*ListRefactorReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{6}
}

func (x *ListRefactorReply) GetInfos() []*RefactorRefactorInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ListRefactorReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RunRefactorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunRefactorRequest) Reset() {
	*x = RunRefactorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRefactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRefactorRequest) ProtoMessage() {}

func (x *RunRefactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRefactorRequest.ProtoReflect.Descriptor instead.
func (*RunRefactorRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{7}
}

type RunRefactorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunRefactorReply) Reset() {
	*x = RunRefactorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRefactorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRefactorReply) ProtoMessage() {}

func (x *RunRefactorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_v1_refactor_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRefactorReply.ProtoReflect.Descriptor instead.
func (*RunRefactorReply) Descriptor() ([]byte, []int) {
	return file_api_analysis_v1_refactor_interface_proto_rawDescGZIP(), []int{8}
}

var File_api_analysis_v1_refactor_interface_proto protoreflect.FileDescriptor

var file_api_analysis_v1_refactor_interface_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x14, 0x52, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x62, 0x65, 0x67, 0x69, 0x6e, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x48, 0x6f, 0x75, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x61,
	0x70, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xab, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x61, 0x70, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x24,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x66,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x66, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x05,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x14, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x2c, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x48, 0x41, 0x4e, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x32, 0xe3, 0x03, 0x0a, 0x11, 0x52, 0x65, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x78, 0x0a,
	0x0d, 0x52, 0x65, 0x63, 0x61, 0x70, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x63, 0x61, 0x70, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x61, 0x70, 0x52, 0x65, 0x66,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x15, 0x12, 0x13, 0x2f, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x75, 0x72, 0x76, 0x65, 0x79, 0x12, 0x70, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x66,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x2f, 0x76, 0x31, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x6e, 0x0a, 0x0c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x72, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x12, 0x72, 0x0a, 0x0b, 0x52, 0x75, 0x6e,
	0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x75, 0x6e, 0x52, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x1a, 0x10, 0x2f, 0x72, 0x65, 0x66, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x75, 0x6e, 0x3a, 0x01, 0x2a, 0x42, 0x20, 0x5a,
	0x1e, 0x70, 0x6f, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_analysis_v1_refactor_interface_proto_rawDescOnce sync.Once
	file_api_analysis_v1_refactor_interface_proto_rawDescData = file_api_analysis_v1_refactor_interface_proto_rawDesc
)

func file_api_analysis_v1_refactor_interface_proto_rawDescGZIP() []byte {
	file_api_analysis_v1_refactor_interface_proto_rawDescOnce.Do(func() {
		file_api_analysis_v1_refactor_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_analysis_v1_refactor_interface_proto_rawDescData)
	})
	return file_api_analysis_v1_refactor_interface_proto_rawDescData
}

var file_api_analysis_v1_refactor_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_analysis_v1_refactor_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_analysis_v1_refactor_interface_proto_goTypes = []interface{}{
	(Status)(0),                  // 0: api.refactor.v1.Status
	(*RefactorRefactorInfo)(nil), // 1: api.refactor.v1.RefactorRefactorInfo
	(*RecapRefactorRequest)(nil), // 2: api.refactor.v1.RecapRefactorRequest
	(*RecapRefactorReply)(nil),   // 3: api.refactor.v1.RecapRefactorReply
	(*GetRefactorRequest)(nil),   // 4: api.refactor.v1.GetRefactorRequest
	(*GetRefactorReply)(nil),     // 5: api.refactor.v1.GetRefactorReply
	(*ListRefactorRequest)(nil),  // 6: api.refactor.v1.ListRefactorRequest
	(*ListRefactorReply)(nil),    // 7: api.refactor.v1.ListRefactorReply
	(*RunRefactorRequest)(nil),   // 8: api.refactor.v1.RunRefactorRequest
	(*RunRefactorReply)(nil),     // 9: api.refactor.v1.RunRefactorReply
}
var file_api_analysis_v1_refactor_interface_proto_depIdxs = []int32{
	0, // 0: api.refactor.v1.RecapRefactorReply.status:type_name -> api.refactor.v1.Status
	1, // 1: api.refactor.v1.GetRefactorReply.info:type_name -> api.refactor.v1.RefactorRefactorInfo
	1, // 2: api.refactor.v1.ListRefactorReply.infos:type_name -> api.refactor.v1.RefactorRefactorInfo
	2, // 3: api.refactor.v1.RefactorInterface.RecapRefactor:input_type -> api.refactor.v1.RecapRefactorRequest
	4, // 4: api.refactor.v1.RefactorInterface.GetRefactor:input_type -> api.refactor.v1.GetRefactorRequest
	6, // 5: api.refactor.v1.RefactorInterface.ListRefactor:input_type -> api.refactor.v1.ListRefactorRequest
	8, // 6: api.refactor.v1.RefactorInterface.RunRefactor:input_type -> api.refactor.v1.RunRefactorRequest
	3, // 7: api.refactor.v1.RefactorInterface.RecapRefactor:output_type -> api.refactor.v1.RecapRefactorReply
	5, // 8: api.refactor.v1.RefactorInterface.GetRefactor:output_type -> api.refactor.v1.GetRefactorReply
	7, // 9: api.refactor.v1.RefactorInterface.ListRefactor:output_type -> api.refactor.v1.ListRefactorReply
	9, // 10: api.refactor.v1.RefactorInterface.RunRefactor:output_type -> api.refactor.v1.RunRefactorReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_analysis_v1_refactor_interface_proto_init() }
func file_api_analysis_v1_refactor_interface_proto_init() {
	if File_api_analysis_v1_refactor_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_analysis_v1_refactor_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefactorRefactorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecapRefactorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecapRefactorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRefactorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRefactorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRefactorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRefactorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRefactorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_analysis_v1_refactor_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRefactorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_analysis_v1_refactor_interface_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_analysis_v1_refactor_interface_proto_goTypes,
		DependencyIndexes: file_api_analysis_v1_refactor_interface_proto_depIdxs,
		EnumInfos:         file_api_analysis_v1_refactor_interface_proto_enumTypes,
		MessageInfos:      file_api_analysis_v1_refactor_interface_proto_msgTypes,
	}.Build()
	File_api_analysis_v1_refactor_interface_proto = out.File
	file_api_analysis_v1_refactor_interface_proto_rawDesc = nil
	file_api_analysis_v1_refactor_interface_proto_goTypes = nil
	file_api_analysis_v1_refactor_interface_proto_depIdxs = nil
}
