server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Wsc12345678=@tcp(127.0.0.1:3306)/analysis
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
ext:
  baidu:
    app_id: jmax2aeel6QbtjLz41KgXcFR
    secret_key: UFAnh9swfOhexrs8juRd6c51hUXFeF3h
  tencent:
    secret_id: AKIDPaVAZhY9TWHlzxe4E7OO8bniMkrgEWXH
    secret_key: UifKjrjJcePs4zd06uRihPq1vYuznKZX
zeek_log:
  dir: '/root/data'
  interval: 2000s
  timeout: 300s
  dir_name_format: '{Y}-{M}-{D}'
  file_name_format: '{type}.{begin_hour}-{end_hour}.log'
  extension: '.gz'