version: '3'

networks:
  poa:

services:
  common-mysql:
    platform: linux/x86_64
    image: mysql
    hostname: common-db
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dangerous
    volumes:
      - ./docker/common/mysql:/var/lib/mysql
    networks:
      - poa
  common-redis:
    image: redis
    ports:
      - "63790:6379"
    volumes:
      - ./docker/common/redis:/data
    networks:
      - poa
#  consul-server1:
#    image: consul
#    container_name: consul-server1
#    volumes:
#      - ./docker/consul/server1.json:/consul/config/server1.json:ro
#    ports:
#      - '8500:8500'
#      - '8600:8600/tcp'
#      - '8600:8600/udp'
#    command: 'agent'
#    networks:
#      - poa
#  consul-client:
#    image: consul
#    container_name: consul-client
#    volumes:
#      - ./docker/consul/client.json:/consul/config/client.json:ro
#    command: 'agent'
#    networks:
#      - poa
#  refactor-service:
#    image: poa-service-app-refactor:0.1.0
#    depends_on:
#      - common-mysql
#      - common-redis
#    hostname: refactor-service
#    networks:
#      - poa
#  analysis-service:
#    image: poa-service-app-analysis:0.1.0
#    depends_on:
#        - common-mysql
#        - common-redis
#    hostname: analysis-service
#    networks:
#      - poa